### PR TITLE
Fix vertical mouse wheel scrolling on PersonCards

### LINKED ISSUE #208: PersonListPanel is unscrollable with mousescroll
When the mouse cursor is over the `contactInfoScrollPane`, scrolling the mouse wheel does not scroll the `PersonListPanel`. 
Scrolling works when the mouse is over the `tutInfosScrollPane`.

### PR DESCRIPTION
**Pull request by Josiah-low**
Mouse wheel scrolling on the contactInfoScrollPane should now scroll the contact list vertically. 

Closes #208

### CODE REVIEW

File: src/main/java/seedu/address/ui/PersonCard.java [hunk 1]
```diff
@@ -108,13 +108,13 @@ private void preventScrollPaneFocusing(ListView<Person> listView) {
...
+     * Redirects vertical scrolling of a ScrollPane to a ListView.
      */
-    private void preventVerticalScroll(ScrollPane scrollPane) {
-        // Solution below inspired by https://stackoverflow.com/a/53991807
+    private void redirectVerticalScroll(ScrollPane scrollPane, ListView<Person> listView) {
         scrollPane.addEventFilter(ScrollEvent.SCROLL, event -> {
             if (event.getDeltaY() != 0) {
-                event.consume();
+                ScrollEvent scrollWheelScrolled = event.copyFor(listView, listView);
+                listView.fireEvent(scrollWheelScrolled);
```
Comment (kelv5) [inline src/main/java/seedu/address/ui/PersonCard.java]: Clean fix to prioritise PersonListPanel scrolling instead of inner components
